<a href="https://colab.research.google.com/github/sharvani1357/Deep-Learning/blob/main/car_price_prediction_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df=pd.read_csv('CarPrice_dataset.csv')

In [4]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [5]:
df.isna().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [6]:
from pandas.core.arrays import Categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
x=df.drop(columns='price')
y=df['price']

#identifying categorical and numerical columns
categorical_cols=x.select_dtypes(include=['object']).columns.tolist()
numerical_cols=x.select_dtypes(include=['int64','float64']).columns.tolist()

#Define Preprocessing steps
preprocessor=ColumnTransformer(
    transformers=[
        ('num',StandardScaler(),numerical_cols),
        ('cat',OneHotEncoder(handle_unknown='ignore'),categorical_cols)
    ])

#apply preprocessing
x_processed=preprocessor.fit_transform(x)

#split the data
x_train,x_test,y_train,y_test=train_test_split(x_processed,y,test_size=0.2,random_state=42)

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#Define the model
model=Sequential([
    Dense(512,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(256,activation='relu'),
    Dense(128,activation='relu'),
    Dense(64,activation='relu'),
    Dense(32,activation='relu'),
    Dense(1)
])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 512)            │       102,912 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 277,505 (1.06 MB)

 Trainable params: 277,505 (1.06 MB)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.compile(optimizer='adam',loss='mean_absolute_error',
              metrics=['mean_absolute_error','mean_squared_error'])

In [13]:
history=model.fit(x_train,y_train,epochs=70,validation_split=0.2,verbose=1)

Epoch 1/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 124ms/step - loss: 312.4153 - mean_absolute_error: 312.4153 - mean_squared_error: 292709.1562 - val_loss: 2162.4072 - val_mean_absolute_error: 2162.4072 - val_mean_squared_error: 9212323.0000
Epoch 2/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 298.3971 - mean_absolute_error: 298.3971 - mean_squared_error: 274782.6875 - val_loss: 2184.8777 - val_mean_absolute_error: 2184.8777 - val_mean_squared_error: 9802533.0000
Epoch 3/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 290.3190 - mean_absolute_error: 290.3190 - mean_squared_error: 251677.0938 - val_loss: 2155.9365 - val_mean_absolute_error: 2155.9365 - val_mean_squared_error: 9147102.0000
Epoch 4/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 298.3910 - mean_absolute_error: 298.3910 - mean_squared_error: 304628.5938 - val_loss: 2182.5330 - val_mean_absolute_error: 2182.5330 - val_mean_squared_error: 9589373.0000
Epoch 5/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 60ms/step - loss: 267.0523 - mean_absolute_error: 267.0523 - mean_squared_error: 219556.2188 - val_loss: 2184.9810 - val_mean_absolute_error: 2184.9810 - val_mean_squared_error: 9806736.0000
Epoch 6/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 290.8020 - mean_absolute_error: 290.8020 - mean_squared_error: 240171.8281 - val_loss: 2180.9265 - val_mean_absolute_error: 2180.9265 - val_mean_squared_error: 9778455.0000
Epoch 7/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 241.6770 - mean_absolute_error: 241.6770 - mean_squared_error: 196777.9375 - val_loss: 2121.6543 - val_mean_absolute_error: 2121.6543 - val_mean_squared_error: 8893712.0000
Epoch 8/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 362.4005 - mean_absolute_error: 362.4005 - mean_squared_error: 326203.6562 - val_loss: 2190.8279 - val_mean_absolute_error: 2190.8279 - val_mean_squared_error: 9266107.0000
Epoch 9/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 299.3811 - mean_absolute_error: 299.3811 - mean_squared_error: 210563.6094 - val_loss: 2185.1421 - val_mean_absolute_error: 2185.1421 - val_mean_squared_error: 9186172.0000
Epoch 10/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 607.3611 - mean_absolute_error: 607.3611 - mean_squared_error: 637869.1250 - val_loss: 2247.0039 - val_mean_absolute_error: 2247.0039 - val_mean_squared_error: 9561969.0000
Epoch 11/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 373.7943 - mean_absolute_error: 373.7943 - mean_squared_error: 424276.0000 - val_loss: 2255.1387 - val_mean_absolute_error: 2255.1387 - val_mean_squared_error: 9392048.0000
Epoch 12/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 334.9651 - mean_absolute_error: 334.9651 - mean_squared_error: 242907.7969 - val_loss: 2203.6472 - val_mean_absolute_error: 2203.6472 - val_mean_squared_error: 9004223.0000
Epoch 13/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 336.8079 - mean_absolute_error: 336.8079 - mean_squared_error: 351568.0625 - val_loss: 2211.1836 - val_mean_absolute_error: 2211.1836 - val_mean_squared_error: 9493379.0000
Epoch 14/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 299.5135 - mean_absolute_error: 299.5135 - mean_squared_error: 198960.7969 - val_loss: 2160.5601 - val_mean_absolute_error: 2160.5601 - val_mean_squared_error: 8978448.0000
Epoch 15/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 251.9542 - mean_absolute_error: 251.9542 - mean_squared_error: 227233.9531 - val_loss: 2217.5601 - val_mean_absolute_error: 2217.5601 - val_mean_squared_error: 9729967.0000
Epoch 16/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 357.6584 - mean_absolute_error: 357.6584 - mean_squared_error: 270657.8750 - val_loss: 2221.9949 - val_mean_absolute_error: 2221.9949 - val_mean_squared_error: 9980861.0000
Epoch 17/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 291.1306 - mean_absolute_error: 291.1306 - mean_squared_error: 308128.2500 - val_loss: 2150.9094 - val_mean_absolute_error: 2150.9094 - val_mean_squared_error: 9276042.0000
Epoch 18/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 235.5333 - mean_absolute_error: 235.5333 - mean_squared_error: 185172.0156 - val_loss: 2202.4502 - val_mean_absolute_error: 2202.4502 - val_mean_squared_error: 9916612.0000
Epoch 19/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 274.4463 - mean_absolute_error: 274.4463 - mean_squared_error: 203383.9844 - val_loss: 2142.8154 - val_mean_absolute_error: 2142.8154 - val_mean_squared_error: 9120739.0000
Epoch 20/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 246.9107 - mean_absolute_error: 246.9107 - mean_squared_error: 172962.0469 - val_loss: 2198.1794 - val_mean_absolute_error: 2198.1794 - val_mean_squared_error: 9638192.0000
Epoch 21/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 285.9286 - mean_absolute_error: 285.9286 - mean_squared_error: 181346.0469 - val_loss: 2154.8579 - val_mean_absolute_error: 2154.8579 - val_mean_squared_error: 9137189.0000
Epoch 22/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 275.4247 - mean_absolute_error: 275.4247 - mean_squared_error: 309927.8750 - val_loss: 2165.1689 - val_mean_absolute_error: 2165.1689 - val_mean_squared_error: 9396059.0000
Epoch 23/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 258.7288 - mean_absolute_error: 258.7288 - mean_squared_error: 294181.6875 - val_loss: 2222.3362 - val_mean_absolute_error: 2222.3362 - val_mean_squared_error: 9831689.0000
Epoch 24/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 268.0238 - mean_absolute_error: 268.0238 - mean_squared_error: 182542.2031 - val_loss: 2149.7544 - val_mean_absolute_error: 2149.7544 - val_mean_squared_error: 8987613.0000
Epoch 25/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 287.8164 - mean_absolute_error: 287.8164 - mean_squared_error: 244996.4688 - val_loss: 2221.2339 - val_mean_absolute_error: 2221.2339 - val_mean_squared_error: 9905073.0000
Epoch 26/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 243.5262 - mean_absolute_error: 243.5262 - mean_squared_error: 161670.1094 - val_loss: 2149.4678 - val_mean_absolute_error: 2149.4678 - val_mean_squared_error: 9258226.0000
Epoch 27/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 221.1413 - mean_absolute_error: 221.1413 - mean_squared_error: 207993.5469 - val_loss: 2165.3816 - val_mean_absolute_error: 2165.3816 - val_mean_squared_error: 9334633.0000
Epoch 28/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 233.3799 - mean_absolute_error: 233.3799 - mean_squared_error: 182339.3750 - val_loss: 2167.8438 - val_mean_absolute_error: 2167.8438 - val_mean_squared_error: 9325500.0000
Epoch 29/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 209.7147 - mean_absolute_error: 209.7147 - mean_squared_error: 206398.1406 - val_loss: 2201.2822 - val_mean_absolute_error: 2201.2822 - val_mean_squared_error: 9775569.0000
Epoch 30/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 243.2732 - mean_absolute_error: 243.2732 - mean_squared_error: 238046.5312 - val_loss: 2139.7324 - val_mean_absolute_error: 2139.7324 - val_mean_squared_error: 9095123.0000
Epoch 31/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 263.3338 - mean_absolute_error: 263.3338 - mean_squared_error: 202217.0781 - val_loss: 2191.9121 - val_mean_absolute_error: 2191.9121 - val_mean_squared_error: 9449598.0000
Epoch 32/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 191.9281 - mean_absolute_error: 191.9281 - mean_squared_error: 134708.0000 - val_loss: 2250.0786 - val_mean_absolute_error: 2250.0786 - val_mean_squared_error: 10215299.0000
Epoch 33/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 265.1555 - mean_absolute_error: 265.1555 - mean_squared_error: 220788.3281 - val_loss: 2184.6624 - val_mean_absolute_error: 2184.6624 - val_mean_squared_error: 9311405.0000
Epoch 34/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 294.5369 - mean_absolute_error: 294.5369 - mean_squared_error: 319473.2500 - val_loss: 2213.9788 - val_mean_absolute_error: 2213.9788 - val_mean_squared_error: 9602691.0000
Epoch 35/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 293.8945 - mean_absolute_error: 293.8945 - mean_squared_error: 263813.5938 - val_loss: 2221.4382 - val_mean_absolute_error: 2221.4382 - val_mean_squared_error: 9512224.0000
Epoch 36/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 231.5514 - mean_absolute_error: 231.5514 - mean_squared_error: 247597.7500 - val_loss: 2219.5625 - val_mean_absolute_error: 2219.5625 - val_mean_squared_error: 9572615.0000
Epoch 37/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 192.5053 - mean_absolute_error: 192.5053 - mean_squared_error: 137770.7031 - val_loss: 2180.8164 - val_mean_absolute_error: 2180.8164 - val_mean_squared_error: 9488355.0000
Epoch 38/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 225.9067 - mean_absolute_error: 225.9067 - mean_squared_error: 330371.9375 - val_loss: 2181.9485 - val_mean_absolute_error: 2181.9485 - val_mean_squared_error: 9824165.0000
Epoch 39/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 231.9396 - mean_absolute_error: 231.9396 - mean_squared_error: 186609.4375 - val_loss: 2223.9175 - val_mean_absolute_error: 2223.9175 - val_mean_squared_error: 9898510.0000
Epoch 40/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 234.5850 - mean_absolute_error: 234.5850 - mean_squared_error: 190194.7031 - val_loss: 2237.1992 - val_mean_absolute_error: 2237.1992 - val_mean_squared_error: 9840074.0000
Epoch 41/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 320.0556 - mean_absolute_error: 320.0556 - mean_squared_error: 237236.3125 - val_loss: 2252.2183 - val_mean_absolute_error: 2252.2183 - val_mean_squared_error: 10046535.0000
Epoch 42/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 499.0226 - mean_absolute_error: 499.0226 - mean_squared_error: 473527.3750 - val_loss: 2114.0190 - val_mean_absolute_error: 2114.0190 - val_mean_squared_error: 8869471.0000
Epoch 43/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 390.4362 - mean_absolute_error: 390.4362 - mean_squared_error: 314766.8125 - val_loss: 2196.8499 - val_mean_absolute_error: 2196.8499 - val_mean_squared_error: 9983366.0000
Epoch 44/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 398.1132 - mean_absolute_error: 398.1132 - mean_squared_error: 463914.0000 - val_loss: 2240.7339 - val_mean_absolute_error: 2240.7339 - val_mean_squared_error: 10302163.0000
Epoch 45/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 272.7451 - mean_absolute_error: 272.7451 - mean_squared_error: 330480.0312 - val_loss: 2252.8274 - val_mean_absolute_error: 2252.8274 - val_mean_squared_error: 10061330.0000
Epoch 46/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 305.8963 - mean_absolute_error: 305.8963 - mean_squared_error: 300307.2500 - val_loss: 2237.2827 - val_mean_absolute_error: 2237.2827 - val_mean_squared_error: 9689309.0000
Epoch 47/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 394.7635 - mean_absolute_error: 394.7635 - mean_squared_error: 360300.2812 - val_loss: 2210.9819 - val_mean_absolute_error: 2210.9819 - val_mean_squared_error: 9809961.0000
Epoch 48/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 268.3007 - mean_absolute_error: 268.3007 - mean_squared_error: 187130.6562 - val_loss: 2127.4900 - val_mean_absolute_error: 2127.4900 - val_mean_squared_error: 9149605.0000
Epoch 49/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 287.5569 - mean_absolute_error: 287.5569 - mean_squared_error: 267665.5938 - val_loss: 2209.9165 - val_mean_absolute_error: 2209.9165 - val_mean_squared_error: 10342189.0000
Epoch 50/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 345.0430 - mean_absolute_error: 345.0430 - mean_squared_error: 251224.9219 - val_loss: 2222.0686 - val_mean_absolute_error: 2222.0686 - val_mean_squared_error: 9847835.0000
Epoch 51/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 334.9404 - mean_absolute_error: 334.9404 - mean_squared_error: 366985.3125 - val_loss: 2293.5720 - val_mean_absolute_error: 2293.5720 - val_mean_squared_error: 10686623.0000
Epoch 52/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 352.5750 - mean_absolute_error: 352.5750 - mean_squared_error: 410275.8438 - val_loss: 2209.8774 - val_mean_absolute_error: 2209.8774 - val_mean_squared_error: 9524955.0000
Epoch 53/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 235.7878 - mean_absolute_error: 235.7878 - mean_squared_error: 179285.9219 - val_loss: 2223.0039 - val_mean_absolute_error: 2223.0039 - val_mean_squared_error: 9847348.0000
Epoch 54/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 230.6984 - mean_absolute_error: 230.6984 - mean_squared_error: 181939.9531 - val_loss: 2162.7209 - val_mean_absolute_error: 2162.7209 - val_mean_squared_error: 9062262.0000
Epoch 55/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 217.9144 - mean_absolute_error: 217.9144 - mean_squared_error: 160404.3594 - val_loss: 2228.0085 - val_mean_absolute_error: 2228.0085 - val_mean_squared_error: 9690472.0000
Epoch 56/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 238.9038 - mean_absolute_error: 238.9038 - mean_squared_error: 302000.6875 - val_loss: 2266.5076 - val_mean_absolute_error: 2266.5076 - val_mean_squared_error: 10359190.0000
Epoch 57/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 215.4289 - mean_absolute_error: 215.4289 - mean_squared_error: 146027.7188 - val_loss: 2228.1431 - val_mean_absolute_error: 2228.1431 - val_mean_squared_error: 10179360.0000
Epoch 58/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 255.1926 - mean_absolute_error: 255.1926 - mean_squared_error: 246440.0156 - val_loss: 2165.6882 - val_mean_absolute_error: 2165.6882 - val_mean_squared_error: 9335118.0000
Epoch 59/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 233.7148 - mean_absolute_error: 233.7148 - mean_squared_error: 166146.5938 - val_loss: 2172.0852 - val_mean_absolute_error: 2172.0852 - val_mean_squared_error: 9387944.0000
Epoch 60/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 289.3947 - mean_absolute_error: 289.3947 - mean_squared_error: 194485.7656 - val_loss: 2206.5767 - val_mean_absolute_error: 2206.5767 - val_mean_squared_error: 9882596.0000
Epoch 61/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 209.1693 - mean_absolute_error: 209.1693 - mean_squared_error: 294719.7812 - val_loss: 2224.5591 - val_mean_absolute_error: 2224.5591 - val_mean_squared_error: 9758523.0000
Epoch 62/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 220.6426 - mean_absolute_error: 220.6426 - mean_squared_error: 161742.2188 - val_loss: 2236.4863 - val_mean_absolute_error: 2236.4863 - val_mean_squared_error: 10093362.0000
Epoch 63/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - loss: 231.5688 - mean_absolute_error: 231.5688 - mean_squared_error: 341015.2188 - val_loss: 2191.0027 - val_mean_absolute_error: 2191.0027 - val_mean_squared_error: 9697224.0000
Epoch 64/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 196.5748 - mean_absolute_error: 196.5748 - mean_squared_error: 183050.6562 - val_loss: 2218.8450 - val_mean_absolute_error: 2218.8450 - val_mean_squared_error: 9878298.0000
Epoch 65/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - loss: 179.2228 - mean_absolute_error: 179.2228 - mean_squared_error: 178175.2031 - val_loss: 2194.5471 - val_mean_absolute_error: 2194.5471 - val_mean_squared_error: 9533683.0000
Epoch 66/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 146.1790 - mean_absolute_error: 146.1790 - mean_squared_error: 110143.0781 - val_loss: 2207.5925 - val_mean_absolute_error: 2207.5925 - val_mean_squared_error: 9868720.0000
Epoch 67/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 195.1311 - mean_absolute_error: 195.1311 - mean_squared_error: 128677.2109 - val_loss: 2162.9231 - val_mean_absolute_error: 2162.9231 - val_mean_squared_error: 9336473.0000
Epoch 68/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 235.4954 - mean_absolute_error: 235.4954 - mean_squared_error: 279977.6562 - val_loss: 2208.5356 - val_mean_absolute_error: 2208.5356 - val_mean_squared_error: 9659232.0000
Epoch 69/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 165.8468 - mean_absolute_error: 165.8468 - mean_squared_error: 112150.0000 - val_loss: 2208.1829 - val_mean_absolute_error: 2208.1829 - val_mean_squared_error: 9655205.0000
Epoch 70/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 161.0994 - mean_absolute_error: 161.0994 - mean_squared_error: 171154.8594 - val_loss: 2205.3840 - val_mean_absolute_error: 2205.3840 - val_mean_squared_error: 9437810.0000

In [14]:
#Model Evaluation
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
y_pred=model.predict(x_test)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print(f'Mean Absolute Error: {mae}')
print(f'Mean Squared Error: {mse}')
print(f'R2 Score: {r2}')

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
Mean Absolute Error: 1831.8674016768293
Mean Squared Error: 8202717.91512232
R2 Score: 0.8960945005876183